AMQP_URI: 'pyamqp://guest:guest@rabbitmq'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10

LOGGING:
    version: 1
    formatters:
        simple:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    loggers:
        simpleExample:
            level: DEBUG
            handlers: [console]
            propagate: no
    root:
        level: DEBUG
        handlers: [console]




